### ISSUE TITLE
Failed to minify the code from this file

### ISSUE THREAD

**Issue by rajatgeekyants** [sindresorhus/to-fast-properties#10]
I am trying to deploy my project on now.sh. But I am getting an error that says:

Failed to minify the code from this file: ./node_modules/to-fast-properties/index.js:3

Here is the code inside the file:
```'use strict';
module.exports = function toFastProperties(obj) {
  function f() {}
  f.prototype = obj;
  new f();
  return;
  eval(obj);
};```

**Comment by sindresorhus** [comment]
This module runs fine in Node.js. If you're having problems, it's the fault of the minimizer.
