### ISSUE TITLE
Tests fail with Node.js >= 12

### ISSUE THREAD

**Issue by nileshpatra** [sindresorhus/to-fast-properties#12]
Hi,
The test fail with Node.js >= 12 with the following log: 
```
[master][~/ups/to-fast-properties]$ npm run test       
(node:21169) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

> to-fast-properties@3.0.0 test /home/nilesh/ups/to-fast-properties
> node --allow-natives-syntax test.js && tsd

  ✖ main   object has fast properties

  ✖ 1 test failed

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! to-fast-properties@3.0.0 test: `node --allow-natives-syntax test.js && tsd`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the to-fast-properties@3.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

seems to fail at this step:

```
t.assert(%HasFastProperties(object), 'object has fast properties');
```

**Comment by benjamingr** [comment]
Sure, this probably needs an update. I'll take a look.

BTW I am not seeing failures on Node 12 - only Node 13:

benjamin@Benjamins-MacBook-Pro to-fast-properties (master) $ nvm use 12
benjamin@Benjamins-MacBook-Pro to-fast-properties (master) $ npm test

> to-fast-properties@3.0.0 test /Users/benjamin/Documents/Projects/to-fast-properties
> node --allow-natives-syntax test.js && tsd

  ✔ main

  ✔ 1 test passed

benjamin@Benjamins-MacBook-Pro to-fast-properties (master) $ nvm use 13
benjamin@Benjamins-MacBook-Pro to-fast-properties (master) $ npm test

> to-fast-properties@3.0.0 test /Users/benjamin/Documents/Projects/to-fast-properties
> node --allow-natives-syntax test.js && tsd

  ✖ main   object has fast properties

  ✖ 1 test failed




Side Note: So, I wanted to check how to fix it (with the V8 unit tests) and I found that oddly this library is included in Chromium's source itself (in the [devtools](https://source.chromium.org/chromium/chromium/src/+/master:third_party/devtools-frontend/src/node_modules/to-fast-properties/index.js?originalUrl=https:%2F%2Fcs.chromium.org%2F)) :D  (and bluebird too)

**Comment by benjamingr** [comment]
Looks like the threshold was changed. Making a pull request.
