### ISSUE TITLE
MIT

### ISSUE THREAD

**Issue by petkaantonov** [sindresorhus/to-fast-properties#3]
I don't want to be a dick but the code is almost verbatim (including the useless eval call that I wrote out of laziness) copied from a MIT licensed project which only has one condition, that you give credit.

**Comment by sindresorhus** [comment]
From what I can remember I extracted this from Babel, but it might have come from somewhere else before that. It's 4 lines so I probably didn't really think much of just copying it. Sorry about that...

How can I fix this? What kind of credit?

## 

Btw, there is some original work in this module: https://github.com/sindresorhus/to-fast-properties/issues/2 https://github.com/sindresorhus/to-fast-properties/commit/dd7184baeb1b2279dda3a86d2c265f00d9595bdf

**Comment by petkaantonov** [comment]
In the license header you just list all the authors starting from the original like this:

```
Copyright (c) <year1> <Original author1>
              <year2> <Original author2>
              <year3> <Your name>

[MIT boilerplate]
```

**Comment by sindresorhus** [comment]
I hope this is what you wanted: https://github.com/sindresorhus/to-fast-properties/commit/3c97b1f9474bff5203d3a602c152ca43a9236e4a If not, let me know :)

**Comment by petkaantonov** [comment]
Yeah looks good, thank you.
