### ISSUE TITLE
No longer works in Node 7+

### ISSUE THREAD

**Issue by jdalton** [sindresorhus/to-fast-properties#6]
Just a heads up this trick no longer works in Node 7+.
Related to https://github.com/petkaantonov/bluebird/issues/1378.

**Comment by jdalton** [comment]
Related t0 https://github.com/petkaantonov/bluebird/issues/1378.

**Comment by benjamingr** [comment]
Opened a PR with the fix, still being more cautious with bluebird targeting .10+ https://github.com/sindresorhus/to-fast-properties/pull/7

**Comment by jdalton** [comment]
Moved to #7.
